### ISSUE TITLE
CESTER_COMMENT doen't print out the message

### ISSUE THREAD

**Issue by chenyulue** [exoticlibraries/libcester#66]
The doc says that  everything in the macro is printed out at the beginning of the test. However, in my environment of mingw64 in msys2 on windows, the following snippet doesn't print the message.

```c
#include <exotic/cester.h>

CESTER_COMMENT(
    This is a multiline comment in \n
    the source code this text is printed out \n
    before any test cases is executed.
)

CESTER_TEST(foo_bar, test_instance,
	cester_assert_cmp_msg(10,>,2,"is 10 greater than 2");
)
	
CESTER_TEST(foo_zoo, test_instance,
	cester_assert_int_gt(1, 2);
)
```

After compiling it with `gcc test.c -I. -o test`, the exe only prints the test results without the comment at the beginning. Am I missing anything?

**Comment by Thecarisma** [comment]
Thank you for bringing that to my notice, I just debug what the issue might be, ends up it only prints out the comment if the output format is specified as text at execution, so the compilation command should give you an output

```c
gcc test.c -I. -o test
./test --cester-verbose
```

This is the expected and not expected behavior, since the default output is text it should print out the comment. I will apply an update to that

**Comment by chenyulue** [comment]
Thanks for your reply! After your hint, I add the following line in the `cester_run_all_test` function:

```c
if (argc == 1) superTestInstance.output_format = (char*)"text";
```

Then it prints out the comment by default.
